General NumPy

### Arrays in Numpy
- homogeneous - only contain 1 data type
- shape must be rectangular

In [72]:
import numpy as np
a = np.array([1, 2, 3, 4,5, 6, 7,8,9,10])
print(a)

a[-1:0:-1]

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [73]:
multiDimArr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(multiDimArr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
multiDimArr[2,2]

np.int64(11)

In [75]:
a.dtype

dtype('int64')

In [76]:
print('Data Type of array: ', multiDimArr.dtype)
print('Data Type of array: ', a.dtype)
print('Data Shape/Dimensions: ', multiDimArr.ndim)
rows, cols = multiDimArr.shape
print('Rows: ', rows)
print('Cols: ', cols)

Data Type of array:  int64
Data Type of array:  int64
Data Shape/Dimensions:  2
Rows:  3
Cols:  4


In [77]:
print(multiDimArr.shape)

(3, 4)


In [78]:
one_to_100 = np.arange(1,100)
print(one_to_100)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [79]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [80]:
sum_arr = arr + 10
print(sum_arr)

[11 12 13 14 15 16 17 18 19 20]


In [81]:
sub_arr = arr - 10
print(sub_arr)

[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]


In [82]:
mult_arr = arr * 10
print(mult_arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [83]:
div_arr = arr/2
print(div_arr)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [84]:
sum =np.sum(arr)
mean = np.mean(arr)
median = np.median(arr)
standard_dev = np.std(arr).round(2)
min = np.min(arr)
max = np.max(arr)
variance = np.var(arr)

print(f'Sum: {sum}')
print(f'Mean: {mean}')
print(f'Median: {median}')
print(f'SD: {standard_dev}')
print(f'Min: {min}')
print(f'Max: {max}')
print(f'variance: {variance}')

Sum: 55
Mean: 5.5
Median: 5.5
SD: 2.87
Min: 1
Max: 10
variance: 8.25


In [85]:
matrix = np.array([[1,2,3],[4,5,6]]) 
print(matrix)

[[1 2 3]
 [4 5 6]]


In [86]:
transposed_matrix = matrix.T
print(transposed_matrix)

[[1 4]
 [2 5]
 [3 6]]


In [87]:
reshaped_matrix = matrix.reshape(3,2)
print(reshaped_matrix)

[[1 2]
 [3 4]
 [5 6]]


#Sorting, Searching and Counting

In [88]:
print(np.argmin(arr))
print(np.argmax(arr))

0
9


In [89]:
newArr = np.array([0,1,2,0,3,0,0,0,2])
print(np.count_nonzero(newArr))
print(np.count_nonzero(newArr)/len(newArr))


4
0.4444444444444444


In [90]:
fruitArr = np.array(['apple','banana','apple','apple','plum','mango','banana'])
print(np.unique(fruitArr))

['apple' 'banana' 'mango' 'plum']


In [91]:
decade1 = np.arange(1980, 1990)
decade2 = np.arange(1990, 2000)
decade3 = np.arange(2000, 2010)

print(decade1)
print(decade2)
print(decade3)
allYears = np.concatenate((decade1,decade2))
print(allYears)

[1980 1981 1982 1983 1984 1985 1986 1987 1988 1989]
[1990 1991 1992 1993 1994 1995 1996 1997 1998 1999]
[2000 2001 2002 2003 2004 2005 2006 2007 2008 2009]
[1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993
 1994 1995 1996 1997 1998 1999]
