### NumPy and Math

In [1]:
import numpy as np

In [2]:
python_list = [1,2,3,4,5]

numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [ ]:
shape = numpy_array.shape
size = numpy_array.size
type = numpy_array.dtype

print(f'1D NumPy Array: {shape}')
print(f'number of Array: {size}')
print(f'type of Array: {type}')


1D NumPy Array: (5,)
number of Array: 5
type of Array: int64


In [8]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([2,4,6,8])

subtraction = arr1-arr2
print(subtraction)

[ 8 16 24 32]


In [10]:
multiplication = arr1*arr2
print(multiplication)
print(multiplication.dtype)

[ 20  80 180 320]
int64


In [12]:
division = arr1/arr2
print(division)
print(division.dtype)

[5. 5. 5. 5.]
float64


In [17]:
data = np.array([85,90,78,92,88,85,95])

min_value = np.min(data)
max_value = np.max(data)
data_range = max_value - min_value
median = np.median(data)
std = np.std(data).round(4)
variance = np.var(data).round(4)

print(f'Min: {min_value}')
print(f'Median: {median}')
print(f'Std: {std}')
print(f'Variance: {variance}')
print(f'Range: {data_range}')

Min: 78
Median: 88.0
Std: 5.1508
Variance: 26.5306
Range: 17


In [ ]:
print(numpy_array)  

[1 2 3 4 5]


In [27]:
slice_array = numpy_array[0:3]
index_condition = numpy_array > 3
index_condition_array = numpy_array[index_condition]
print(slice_array)
print(index_condition)
print(f'Array based on codition: {index_condition_array}')

[1 2 3]
[False False False  True  True]
Array based on codition: [4 5]
