### NumPy and Math

In [30]:
import numpy as np

In [31]:
python_list = [1,2,3,4,5]

numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [32]:
shape = numpy_array.shape
size = numpy_array.size
type = numpy_array.dtype

print(f'1D NumPy Array: {shape}')
print(f'number of Array: {size}')
print(f'type of Array: {type}')


1D NumPy Array: (5,)
number of Array: 5
type of Array: int64


In [33]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([2,4,6,8])

subtraction = arr1-arr2
print(subtraction)

[ 8 16 24 32]


In [34]:
multiplication = arr1*arr2
print(multiplication)
print(multiplication.dtype)

[ 20  80 180 320]
int64


In [35]:
division = arr1/arr2
print(division)
print(division.dtype)

[5. 5. 5. 5.]
float64


In [36]:
data = np.array([85,90,78,92,88,85,95])

min_value = np.min(data)
max_value = np.max(data)
data_range = max_value - min_value
median = np.median(data)
std = np.std(data).round(4)
variance = np.var(data).round(4)

print(f'Min: {min_value}')
print(f'Median: {median}')
print(f'Std: {std}')
print(f'Variance: {variance}')
print(f'Range: {data_range}')

Min: 78
Median: 88.0
Std: 5.1508
Variance: 26.5306
Range: 17


In [37]:
print(numpy_array)  

[1 2 3 4 5]


In [38]:
slice_array = numpy_array[0:3]
index_condition = numpy_array > 3
index_condition_array = numpy_array[index_condition]
print(slice_array)
print(index_condition)
print(f'Array based on codition: {index_condition_array}')

[1 2 3]
[False False False  True  True]
Array based on codition: [4 5]


In [39]:
combined_result = numpy_array[1:4][numpy_array[1:4]>3]
print(f'OG array: {numpy_array}')
print(f'combined_result: {combined_result}')

OG array: [1 2 3 4 5]
combined_result: [4]


In [40]:
temperature_data = np.array(
    [22.3, 23.1,
    24.5, 25.8, 23.6, 26.7,
    27.9, 29.2, 30.5, 24.7,
    23.4, 22.1, 25.3, 26.4,
    28.7, 29.8, 31.2, 32.4,
    30.7, 29.5, 27.8, 26.6,
    23.9, 22.5, 24.1, 25.7,
    27.3, 29.6, 31.0, 33.1,
    31.9
    ]
)
meantemp = np.mean(temperature_data)
median = np.median(temperature_data)
std = np.std(temperature_data)


In [41]:
print(f'Mean: {meantemp}')
print(f'Median: {median}')
print(f'Standard Deviation: {std}')

Mean: 27.138709677419353
Median: 26.7
Standard Deviation: 3.221668313492935


In [42]:
Ftemp = temperature_data*9/5 +32
print(Ftemp)

[72.14 73.58 76.1  78.44 74.48 80.06 82.22 84.56 86.9  76.46 74.12 71.78
 77.54 79.52 83.66 85.64 88.16 90.32 87.26 85.1  82.04 79.88 75.02 72.5
 75.38 78.26 81.14 85.28 87.8  91.58 89.42]


In [45]:
hotdays = temperature_data[temperature_data>30]
print(f'Hot day: {hotdays}')
print(f'Num of hot days: {len(hotdays)}')

Hot day: [30.5 31.2 32.4 30.7 31.  33.1 31.9]
Num of hot days: 7


In [49]:
base_temp = 20
cooling_degree_total = np.sum(np.maximum(temperature_data-base_temp,0))
print(f'Cooling degree total: {cooling_degree_total}')

Cooling degree total: 221.3
